- name : assembly boxfuse 1
  hosts: web
  become: yes
  vars:
    repo_url: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    workspace: /usr/boxfuse

  tasks:
  - name: Ensure jdk package is present
    apt:
     name: default-jdk
     state: present

  - name: Ensure git package is present
    apt:
     name: git
     state: present

  - name: Ensure maven package is present
    apt:
     name: maven
     state: present

  - name: Git clone boxfuse
    git:
     repo: "{{ repo_url }}"
     dest: "{{ workspace }}"

  - name: Build application
    shell: mvn package chdir="{{ workspace }}"
    run_once: true

  - name: Copy war from remote server
    fetch:
    run_once: true
     src: /usr/boxfuse/target/
     dest: /tmp
    with_fileglob: /usr/boxfuse/target/*.war


- name : run tomcat and application
  hosts: db
  become : yes

  tasks: 
  - name: Ensure tomcat is present
    apt: 
     name: tomcat9
     state: present