- name : assembly boxfuse 1
  hosts: web
  become: yes
  vars:
    repo_url: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    workspace: /usr/boxfuse

  tasks:
  - name: Ensure jdk package is present
    apt:
     name: default-jdk
     state: present

  - name: Ensure git package is present
    apt:
     name: git
     state: present

  - name: Ensure maven package is present
    apt:
     name: maven
     state: present

  - name: Git clone boxfuse
    git:
     repo: "{{ repo_url }}"
     dest: "{{ workspace }}"

  - name: Build application
    shell: mvn package chdir="{{ workspace }}"
    run_once: true

  - name: Copy war from remote server
    fetch:
     src: /usr/boxfuse/target/hello-1.0.war
     dest: /tmp
 
 
  - name : run tomcat and application
  hosts: db
  become : yes

  tasks: 
  - name: Ensure tomcat is present
    apt: 
     name: tomcat9
     state: present
  
  - name: copy war from local to db server
    copy:
     src: /tmp/34.105.177.150/usr/boxfuse/target/hello-1.0.war
     dst: /var/lib/tomcat9/webapps